import { Product } from "../types/product";
import { ProductHighlights } from "../types/productHighlights";

export const mockProducts: Product[] = [
    {
        id: 1,
        name: "Dead by Daylight",
        image: "/test/t1/i0.jpg",
        lowest_price: 49.90,
        highest_price: 49.90,
    },
    {
        id: 2,
        name: "Assassin's Creed Odyssey",
        image: "/test/t2/i0.jpg",
        lowest_price: 109.90,
        highest_price: 140.90,
    },
    {
        id: 3,
        name: "Minecraft Bedrock Edition",
        image: "/test/t3/i0.jpg",
        lowest_price: 109.90,
        highest_price: 109.90,
    },
    {
        id: 4,
        name: "God of War",
        image: "/test/t4/i0.jpg",
        lowest_price: 47.50,
        highest_price: 47.50,
    },
    {
        id: 5,
        name: "The Crew Motorfest",
        image: "/test/t5/i0.jpg",
        lowest_price: 109.90,
        highest_price: 140.90,
    },
    {
        id: 6,
        name: "The Texas Chain Saw Massacre",
        image: "/test/t6/i0.jpg",
        lowest_price: 109.90,
        highest_price: 109.90,
    },
    {
        id: 7,
        name: "Grand Theft Auto V",
        image: "/test/t7/i0.jpg",
        lowest_price: 89.90,
        highest_price: 89.90,
    },
    {
        id: 8,
        name: "Dark Souls III",
        image: "/test/t8/i0.jpg",
        lowest_price: 95.00,
        highest_price: 95.00,
    },
    {
        id: 9,
        name: "Elden Ring",
        image: "/test/t9/i0.jpg",
        lowest_price: 199.90,
        highest_price: 249.90,
    },
    {
        id: 10,
        name: "EA Sports FC 25",
        image: "/test/t10/i0.jpg",
        lowest_price: 179.90,
        highest_price: 229.90,
    },
    {
        id: 11,
        name: "Red Dead Redemption 2",
        image: "/test/t11/i0.jpg",
        lowest_price: 89.90,
        highest_price: 119.90,
    },
    {
        id: 12,
        name: "Doom",
        image: "/test/t12/i0.jpg",
        lowest_price: 79.90,
        highest_price: 99.90,
    },
    {
        id: 13,
        name: "Ori and the will of the wisps",
        image: "/test/t13/i0.jpg",
        lowest_price: 75.00,
        highest_price: 75.00,
    },
    {
        id: 14,
        name: "Star Wars Jedi: Fallen Order",
        image: "/test/t14/i0.jpg",
        lowest_price: 249.90,
        highest_price: 299.90,
    },
    {
        id: 15,
        name: "Overcooked! 2",
        image: "/test/t15/i0.jpg",
        lowest_price: 29.90,
        highest_price: 89.90,
    },
    {
        id: 16,
        name: "Rivals of Aether",
        image: "/test/t16/i0.jpg",
        lowest_price: 99.90,
        highest_price: 129.90,
    },
    {
        id: 17,
        name: "Slackers: Carts of Glory",
        image: "/test/t17/i0.jpg",
        lowest_price: 89.90,
        highest_price: 89.90,
    },
    {
        id: 18,
        name: "Cuphead",
        image: "/test/t18/i0.jpg",
        lowest_price: 95.00,
        highest_price: 95.00,
    },
    {
        id: 19,
        name: "SpeedRunners",
        image: "/test/t19/i0.jpg",
        lowest_price: 199.90,
        highest_price: 249.90,
    },
    {
        id: 20,
        name: "Duck Game",
        image: "/test/t20/i0.jpg",
        lowest_price: 179.90,
        highest_price: 229.90,
    },
    {
        id: 21,
        name: "Tomb Raider",
        image: "/test/t21/i0.jpg",
        lowest_price: 89.90,
        highest_price: 119.90,
    },
    {
        id: 22,
        name: "Rounds",
        image: "/test/t22/i0.jpg",
        lowest_price: 79.90,
        highest_price: 99.90,
    },
    {
        id: 23,
        name: "Hollow Knight: Silksong",
        image: "/test/t23/i0.jpg",
        lowest_price: 75.00,
        highest_price: 75.00,
    },
    {
        id: 24,
        name: "Hytale",
        image: "/test/t24/i0.jpg",
        lowest_price: 249.90,
        highest_price: 299.90,
    },
    {
        id: 25,
        name: "Broforce",
        image: "/test/t25/i0.jpg",
        lowest_price: 29.90,
        highest_price: 89.90,
    },
    {
        id: 26,
        name: "007 Legends",
        image: "/test/t26/i0.jpg",
        lowest_price: 99.90,
        highest_price: 229.90,
    },
    {
        id: 27,
        name: "Bully",
        image: "/test/t27/i0.jpg",
        lowest_price: 89.90,
        highest_price: 89.90,
    },
    {
        id: 28,
        name: "Dead Space 2",
        image: "/test/t28/i0.jpg",
        lowest_price: 95.00,
        highest_price: 95.00,
    },
];

export const mockHighlights: ProductHighlights[] = [
    {
        id: 3,
        name: "Multiplayer",
        products: [
            {
                id: 15,
                name: "Overcooked! 2",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t15/i1.webp",
                lowest_price: 29.90,
                highest_price: 89.90,
            },
            {
                id: 16,
                name: "Rivals of Aether",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t16/i1.webp",
                lowest_price: 99.90,
                highest_price: 129.90,
            },
            {
                id: 5,
                name: "The Crew Motorfest",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t5/i1.webp",
                lowest_price: 109.90,
                highest_price: 140.90,
            },
            {
                id: 13,
                name: "Ori and the will of the wisps",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t13/i1.webp",
                lowest_price: 75.00,
                highest_price: 75.00,
            },
            {
                id: 14,
                name: "Star Wars Jedi: Fallen Order",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t14/i1.webp",
                lowest_price: 249.90,
                highest_price: 299.90,
            },
            {
                id: 17,
                name: "Slackers: Carts of Glory",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t17/i1.webp",
                lowest_price: 89.90,
                highest_price: 89.90,
            },
            {
                id: 18,
                name: "Cuphead",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t18/i1.webp",
                lowest_price: 95.00,
                highest_price: 95.00,
            },
            {
                id: 6,
                name: "The Texas Chain Saw Massacre",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t6/i1.webp",
                lowest_price: 109.90,
                highest_price: 109.90,
            },
        ],
    },
    {
        id: 1,
        name: "Lançamentos",
        products: [
            {
                id: 19,
                name: "SpeedRunners",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t19/i1.webp",
                lowest_price: 199.90,
                highest_price: 249.90,
            },
            {
                id: 20,
                name: "Duck Game",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t20/i1.webp",
                lowest_price: 179.90,
                highest_price: 229.90,
            },
            {
                id: 21,
                name: "Tomb Raider",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t21/i1.webp",
                lowest_price: 89.90,
                highest_price: 119.90,
            },
            {
                id: 22,
                name: "Rounds",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t22/i1.webp",
                lowest_price: 79.90,
                highest_price: 99.90,
            },
            {
                id: 23,
                name: "Hollow Knight: Silksong",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t23/i1.webp",
                lowest_price: 75.00,
                highest_price: 75.00,
            },
            {
                id: 24,
                name: "Hytale",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t24/i1.webp",
                lowest_price: 249.90,
                highest_price: 299.90,
            },
            {
                id: 1,
                name: "Dead by Daylight",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t1/i1.webp",
                lowest_price: 49.90,
                highest_price: 49.90,
            },
            {
                id: 2,
                name: "Assassin's Creed Odyssey",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t2/i1.webp",
                lowest_price: 109.90,
                highest_price: 140.90,
            },
        ],
    },
    {
        id: 5,
        name: "Saindo em breve",
        products: [
            {
                id: 23,
                name: "Hollow Knight: Silksong",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t23/i1.webp",
                lowest_price: 75.00,
                highest_price: 75.00,
            },
            {
                id: 24,
                name: "Hytale",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t24/i1.webp",
                lowest_price: 249.90,
                highest_price: 299.90,
            },
            {
                id: 19,
                name: "SpeedRunners",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t19/i1.webp",
                lowest_price: 199.90,
                highest_price: 249.90,
            },
            {
                id: 20,
                name: "Duck Game",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t20/i1.webp",
                lowest_price: 179.90,
                highest_price: 229.90,
            },
            {
                id: 21,
                name: "Tomb Raider",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t21/i1.webp",
                lowest_price: 89.90,
                highest_price: 119.90,
            },
            {
                id: 22,
                name: "Rounds",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t22/i1.webp",
                lowest_price: 79.90,
                highest_price: 99.90,
            },
            {
                id: 1,
                name: "Dead by Daylight",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t1/i1.webp",
                lowest_price: 49.90,
                highest_price: 49.90,
            },
            {
                id: 2,
                name: "Assassin's Creed Odyssey",
                description: "Resident Evil Requiem is the ninth entry in the Resident Evil series. Experience terrifying survival horror with FBI analyst Grace Ashcroft, and dive into pulse-pounding action with legendary agent Leon S. Kennedy. Both of their journeys and unique gameplay styles intertwine into a heart-stopping, emotional experience that will chill you to your core.",
                image: "/test/t2/i1.webp",
                lowest_price: 109.90,
                highest_price: 140.90,
            },
        ],
    },
];